### ISSUE TITLE
Whether other games are supported？

### ISSUE THREAD

**Issue by x4317350** [xforce/neox-tools#1]

**Comment by xforce** [comment]
Hey, I do not speak chinese, but as far as I can translate you are talking about a 64bit version of some client?

What client are you talking about specifically?
Or are you asking for me to provide pre-built binaries?

**Comment by x4317350** [comment]
hey,you can download the 64bit client from this webpage
https://yys.163.com/
this client's script.npk is update.
i can't unpack it wiht your npktool.

**Comment by x4317350** [comment]
> Hey, I do not speak chinese, but as far as I can translate you are talking about a 64bit version of some client?
> 
> What client are you talking about specifically?
> Or are you asking for me to provide pre-built binaries?

hey,you can download the 64bit client from this webpage
https://yys.163.com/
this client's script.npk is update.
i can't unpack it wiht your npktool.

**Comment by xforce** [comment]
Ah, I see.
Yes currently only Eve Echoes is supported, since that was the game I started with and was the primary driver for the existence of this.
But have been looking at support all the npk variants in the future (as noted in the Readme).
I will be taking a look at the sample you linked and update this tool later today to add support for that archive.

**Comment by x4317350** [comment]
> Ah, I see.
> Yes currently only Eve Echoes is supported, since that was the game I started with and was the primary driver for the existence of this.
> But have been looking at support all the npk variants in the future (as noted in the Readme).
> I will be taking a look at the sample you linked and update this tool later today to add support for that archive.

you can try decrypt this pyc file.
maybe,the opcode is changed

[redirect.pyc.zip](https://github.com/xforce/neox-tools/files/5121647/redirect.pyc.zip)

**Comment by xforce** [comment]
I do not have a list of games that are supported, but since 7ca1cc78c2bf42118edd76a31e17268109a7cfd2 I am also supporting the older NPK format, which _should_ make this tool work with a lot more games.

If you require further assistance, please open a new issue with specific games/sample files that don't work and I will try to see what can be done to support those as well.
